### PR TITLE
add filter option

### PR DESCRIPTION
**Pull request by ItsNickBarry**
Discussed in #25 and #20.

### CODE REVIEW

**Comment by ItsNickBarry** [comment]
Should the `filter` function accept any additional parameters, or just standard `Array#filter`?  For example, contract name or artifact path.

**Comment by phated** [comment]
For the Dark Forest subgraph use case, we can do all filter based on just the ABI information, but I definitely think there could be value in passing in the fullyQualifiedName. In `hardhat-diamond-abi`, the filter signature is `filter(fullyQualifiedName: string, abi: any) => bool`

**Comment by ItsNickBarry** [comment]
@phated See latest.  I've structured it as a callback passed to `abi.filter(...)` rather than a function that accepts the entire ABI and returns a filtered result.  I think it's a bit more intuitive and concise this way.

**Review by phated — APPROVED** [review]
👍 @ItsNickBarry I like this! I actually will probably align my plugin's `filter` option like this. I like the idea that someone could access the entire ABI if they need it.

**Comment by ItsNickBarry** [comment]
It's likely that nobody will ever use the full ABI here, but I included it because `Array#filter` passes `element`, `index`, and the full `array` to the callback.

**Pull request merged**
