### PR TITLE
Allow external dir and multiple file paths

### PR DESCRIPTION
**Pull request by Thrasymachus01**
Allows a user to specify multiple file paths to write to and also an option to enable writing to paths outside of the current hardhat directory - by default this is set to `false`.

### CODE REVIEW

**Comment by ItsNickBarry** [comment]
What is your use case for exporting to an external directory?

**Comment by Thrasymachus01** [comment]
We have 3 repos. 1 for backend, 1 for frontend and 1 for the smart contracts. 
On deploy we have all three codebases updated with the new contracts/abis.

**Comment by ItsNickBarry** [comment]
I would suggest one of the following:

1. Add your smart contract repository as a dependency of the other respositories and load the ABIs through a package manager (NPM).

2. Override the `compile` task and copy the ABI export directory manually:

```javascript
const fs = require('fs-extra');

const { TASK_COMPILE } = require('hardhat/builtin-tasks-task-names');

task(TASK_COMPILE, async function (args, hre, runSuper) {
  await runSuper();

  fs.emptyDirSync(EXTERNAL_DIRECTORY_0);
  fs.copySync(hre.config.abiExporter.path, EXTERNAL_DIRECTORY_0);
  fs.emptyDirSync(EXTERNAL_DIRECTORY_1);
  fs.copySync(hre.config.abiExporter.path, EXTERNAL_DIRECTORY_1);
});
```

**Comment by Thrasymachus01** [comment]
Loading through a tool like NPM or even pushing to git isnt really an option as it will become super tedious when debugging/developing a contract early in its dev lifecycle. e.g. make a tweak, upload to npm, download - it didnt work, repeat until bug is fixed...

Second option seems fine, but for the less experienced dev or even a dev who is experienced but isn't as familiar with the node fs apis (and has to google for the docs) it can be a problem. imo it's easier to just specify in the config: 

```
{
    allowExternalDir: true,
    path: [path1, path2, path3]
}
```

**Comment by ItsNickBarry** [comment]
In that case I would recommend `npm link` or `yarn link` to enable development against the local version of the dependencies.

I'm reluctant to allow the emptying of directories outside of the hardhat project, especially if we're talking about the "less experienced dev".  Closing for now, but open to further arguments.  You can of course add your fork as a dependency of your project instead of the `hardhat-abi-exporter` package.

**Pull request closed without merging**
